# Generated by Django 4.0.6 on 2022-08-18 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guiclient', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flavors',
            new_name='Flavor',
        ),
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Networks',
            new_name='Network',
        ),
        migrations.RenameModel(
            old_name='Routers',
            new_name='Router',
        ),
        migrations.RenameModel(
            old_name='Servers',
            new_name='Server',
        ),
        migrations.RenameModel(
            old_name='Subnets',
            new_name='Subnet',
        ),
    ]
